name: alugo
description: "Alugo - Encontre quartos universitários."
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Required for localization if you plan to support multiple languages
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2 # For iOS style icons
  lucide_flutter: ^0.400.0 # Icon library (Flutter equivalent for lucide-react)
  google_fonts: ^6.1.0 # For custom fonts, SF Pro not directly available, will use similar open-source

  # State Management
  provider: ^6.0.5

  # Navigation
  # go_router: ^13.0.1 # Consider for more complex navigation

  # Networking
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Image Handling
  cached_network_image: ^3.3.0

  # Date Formatting
  intl: ^0.19.0

  # Maps
  google_maps_flutter: ^2.5.0
  # geolocator: ^11.0.0 # For user location if needed
  # flutter_polyline_points: ^2.0.0 # For drawing routes on map if Directions API is used directly

  # Other Utilities
  # url_launcher: ^6.1.14 # For opening links
  flutter_svg: ^2.0.9 # If using SVG for logo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #   - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
